- There are some edits here that have removed escape characters. This was done due to the following errors.
```
    "found unknown escape character %r" % ch.encode('utf-8'), self.get_mark())
yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "/etc/jenkins_jobs/jobs/data_sync.yaml", line 38, column 26
found unknown escape character "'"
  in "/etc/jenkins_jobs/jobs/data_sync.yaml", line 39, column 52```

```
    "found unknown escape character %r" % ch.encode('utf-8'), self.get_mark())
yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "/etc/jenkins_jobs/jobs/data_sync.yaml", line 44, column 26
found unknown escape character "'"
  in "/etc/jenkins_jobs/jobs/data_sync.yaml", line 44, column 47```

```
    "found unknown escape character %r" % ch.encode('utf-8'), self.get_mark())
yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "/etc/jenkins_jobs/jobs/data_sync.yaml", line 47, column 26
found unknown escape character "'"
  in "/etc/jenkins_jobs/jobs/data_sync.yaml", line 47, column 71```

```
    "found unknown escape character %r" % ch.encode('utf-8'), self.get_mark())
yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "/etc/jenkins_jobs/jobs/data_sync.yaml", line 50, column 26
found unknown escape character "'"
  in "/etc/jenkins_jobs/jobs/data_sync.yaml", line 50, column 60```

```
    "found unknown escape character %r" % ch.encode('utf-8'), self.get_mark())
yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "/etc/jenkins_jobs/jobs/data_sync.yaml", line 65, column 26
found unknown escape character "'"
  in "/etc/jenkins_jobs/jobs/data_sync.yaml", line 65, column 60```

Pair: @schmie @suthagarht