[#68346578] Set a TLD for the development VM
So that `facter fqdn` and Puppet's `$::fqdn` works. To fix this error, seen
by @jordanhatch, amongst others:
```
Error: Parameter name failed on Mysql_user[root@]: Invalid database user root@ at /var/govuk/puppet/vendor/modules/mysql/manifests/server/account_security.pp:11
Wrapped exception:
Invalid database user root@
```

I think this has always been slightly broken. But we wouldn't have noticed that
particular issue until 42bdc7f.