Revert #2675: remove gem autoload monkey patch
This reverts commit 8e1f84c8ef65400cc011fb71950cba6f9d1a8893.

Reverting this pull request because it prevents the dev VM from
provisioning correctly, producing the following error:

```
INFO: running puppet
Warning: Setting manifestdir is deprecated. See http://links.puppetlabs.com/env-settings-deprecations
   (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1095:in `block in issue_deprecations')
Warning: Setting modulepath is deprecated in puppet.conf. See http://links.puppetlabs.com/env-settings-deprecations
   (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1095:in `block in issue_deprecations')
Warning: Setting config_version is deprecated in puppet.conf. See http://links.puppetlabs.com/env-settings-deprecations
   (at /usr/lib/ruby/vendor_ruby/puppet/settings.rb:1095:in `block in issue_deprecations')
Error: wrong number of arguments (2 for 1)
```

Reverting this change allows puppet to run cleanly.