Correct indentation in jenkins job yaml
Currently we can't apply this configuration because the yaml parser
throws an exception:

     yaml.scanner.ScannerError: mapping values are not allowed here