[#65900624] Add hiera disks for s_backup
So that it stops complaining about a missing mount resource:
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid relationship: Class[Backup::Server] { require => Govuk::Mount[/data/backups] }, because Govuk::Mount[/data/backups] doesn't seem to be in the catalog
```

This matches the existing machine in Platform1:
```
dcarley@production-backup-1:~$ sudo pvs /dev/sdb1
  PV         VG      Fmt  Attr PSize   PFree
  /dev/sdb1  backups lvm2 a-   256.00g    0
dcarley@production-backup-1:~$ grep backup /proc/mounts
/dev/mapper/backups-data /data/backups ext4 rw,relatime,errors=remount-ro,data=ordered 0 0
```