Remove require for an exported resource
Exported resources shouldnt require things on other machines to exist.

Removing this require due to the following error on monitoring-1
```
Error: Could not retrieve catalog from remote server: Error 400 on
SERVER: Invalid relationship:
Icinga::Passive_check[check_es_rotate_logs-elasticsearch-2] { require =>
File[/usr/local/bin/es-rotate-passive-check] }, because
File[/usr/local/bin/es-rotate-passive-check] doesn't seem to be in the
catalog
```