Disable mongodb backups on dev VM.
This is currently erroring with:

Error: This machine's hostname was not found in the list of MongoDB
replicaset members: localhost at
/var/govuk/puppet/modules/mongodb/manifests/backup.pp:27 on node
development.development

This is due to the way the mongo cluster is configured on the dev VM.
Instead of resolving this, it's simplest to skip the backups here as
there's no need for them.