Pin packages before installing Puppet
Set the pins before installing Puppet and Facter. Otherwise APT will refuse to
change the version when requested:
```
Error: /Stage[main]/Puppet::Package/Package[puppet]/ensure: change from 3.2.3-1puppetlabs1 to 3.4.3-1puppetlabs1 failed: Could not update: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-c
onfold --force-yes install puppet=3.4.3-1puppetlabs1' returned 100: Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 puppet : Depends: puppet-common (= 3.4.3-1puppetlabs1) but 3.2.3-1puppetlabs1 is to be installed
E: Unable to correct problems, you have held broken packages.

Notice: /Stage[main]/Puppet::Package/Package[puppet-common]: Dependency Package[puppet] has failures: true
Warning: /Stage[main]/Puppet::Package/Package[puppet-common]: Skipping because of failed dependencies
Notice: /Stage[main]/Puppet::Package/Exec[remove_puppet_gem]: Dependency Package[puppet] has failures: true
Warning: /Stage[main]/Puppet::Package/Exec[remove_puppet_gem]: Skipping because of failed dependencies
Notice: /Stage[main]/Puppet::Package/File[/usr/bin/puppet]: Dependency Package[puppet] has failures: true
Warning: /Stage[main]/Puppet::Package/File[/usr/bin/puppet]: Skipping because of failed dependencies
Notice: /Stage[main]/Puppet::Package/File[/usr/local/bin/puppet]: Dependency Package[puppet] has failures: true
Warning: /Stage[main]/Puppet::Package/File[/usr/local/bin/puppet]: Skipping because of failed dependencies
Notice: /Stage[main]/Puppet::Package/Exec[remove_facter_gem]: Dependency Package[puppet] has failures: true
Warning: /Stage[main]/Puppet::Package/Exec[remove_facter_gem]: Skipping because of failed dependencies
Notice: /Stage[main]/Puppet::Package/Exec[remove_hiera_gem]: Dependency Package[puppet] has failures: true
Warning: /Stage[main]/Puppet::Package/Exec[remove_hiera_gem]: Skipping because of failed dependencies
Notice: /Stage[main]/Puppet::Package/Apt::Pin[prevent_puppet_breakage]/File[prevent_puppet_breakage.pref]/content:
--- /etc/apt/preferences.d/prevent_puppet_breakage.pref 2014-03-17 15:29:08.392759745 +0000
+++ /tmp/puppet-file20140317-2321-1one8dn       2014-03-17 16:46:40.263147512 +0000
@@ -1,5 +1,5 @@
 # prevent_puppet_breakage
 Explanation: : prevent_puppet_breakage
 Package: puppet-common puppet
-Pin: version 3.2.3-1puppetlabs1
+Pin: version 3.4.3-1puppetlabs1
 Pin-Priority: 1001
```