Set up `/etc/nginx/ssl` directory
This directory is required to store SSL certificates and keys, but
isn't provided by the nginx-common or nginx-full packages.

Puppet appears to create it on some machines:

```
syslog.2.gz:Jul 23 10:28:01 calculators-frontend-1 puppet-agent[1671]:
  (/Stage[main]/Nginx::Config/File[/etc/nginx/ssl]/ensure) created
```

But doesn't on others:

```
Error: Could not set 'present' on ensure: No such file or directory -
  /etc/nginx/ssl/whitehall.staging.publishing.service.gov.uk.key20150726-10462-12vs2kg.lock
  at 60:/usr/share/puppet/production/current/modules/nginx/manifests/config/ssl.pp
```