Ensure MySQL backup parameters are strings
I fixed these parameters in dcb5fef479a86a6dc9218060c3d6dc607110b65a
since they weren't being used, but it turns out that they need to
be strings:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Failed to parse template automysqlbackup/automysqlbackup.conf.erb:
  Filepath: /usr/share/puppet/production/current/vendor/modules/automysqlbackup/templates/automysqlbackup.conf.erb
  Line: 9
  Detail: undefined method `empty?' for 2:Fixnum
 at /usr/share/puppet/production/current/vendor/modules/automysqlbackup/manifests/backup.pp:197 on node mysql-backup-1.backend.production
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```