Revert "Upgrade saz/rsyslog to 3.5.1"
This reverts commit 2ce9e2a51486841977ef7161b82ea762b99f9656.

There are problems with the logging machine which I should have done more
testing on before updating the rsyslog module. The error is:

```
Failed to parse template govuk/etc/rsyslog.d/server-logstash.conf.erb:
  Filepath: /opt/rubies/1.9.3-p545/lib/ruby/gems/1.9.1/gems/puppet-3.6.2/lib/puppet/parser/functions/template.rb
  Line: 19
  Detail: Failed to parse template rsyslog/server/_default-header.conf.erb:
  Filepath: /opt/rubies/1.9.3-p545/lib/ruby/gems/1.9.1/gems/puppet-3.6.2/lib/puppet/util/package.rb
  Line: 4
  Detail: undefined method `scan' for nil:NilClass

at /Users/alexmuller/govuk/puppet/vendor/modules/rsyslog/manifests/server.pp:69 on node logging-1.example.com> with backtrace:
```

As Puppet isn't running on the logging machines I'd rather revert
this commit and take more time to test this change.