Install token-macro Jenkins plugin
This plugin is a dependency of the `build-name-setter` plugin.

```
SEVERE: Failed Loading plugin build-name-setter
java.io.IOException: Dependency token-macro (1.0) doesn't exist
```