Reinstate libffi-dev on deploy.* for analytics
This package was removed from the deploy Jenkins in 5797fba because the
project that it was originally added for in bc511cf, govuk_spider and
Scrapy, was no longer in use.

It was then noted in #2185 that the search-fetch-analytics-data job on
deploy.production, from alphagov/search-analytics, depends on this when
installing the `cryptography` package from pypi:
```
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -c _configtest.c -o _configtest.o
success!
removing: _configtest.c _configtest.o
c/_cffi_backend.c:13:17: fatal error: ffi.h: No such file or directory
compilation terminated.
```

So reinstate it with an updated comment.