Update hiera-puppet-helper and remove monkey patch
This is a partial revert of 32b7e56 which monkey-patched the part of Puppet
that does automatic param lookups from hiera. Besides the simplicity of not
monkey-patching, my hope is that this will allow us to provide mandatory
params for classes that are included and not directly under test.

The bobtfish fork of hiera-puppet-helper appears to be better maintained
than mthibaut's (which it was forked from) and amfranz's (the original
author who has stated they're no longer supporting it). However it's not
published to rubygems so we need to reference the repo. It includes:

- bobtfish/hiera-puppet-helper@d6dfc04cdba283ccea1bf7ed41148bc711361fcb

  Which fixes our monkey-patch.

- bobtfish/hiera-puppet-helper@cd5b26f65155668eabb2beabebbd4bffead79004

  Which is what Matt forked it for in bb63380.

It appears to be important that `hiera-puppet-helper` is loaded *after*
`puppetlabs_spec_helper` otherwise the tests fail with the following error:

    Failure/Error: Unable to find matching line from backtrace
    NoMethodError:
     undefined method `proxy_for' for nil:NilClass
    # /Users/dcarley/vendor/bundle/gems/rspec-mocks-2.14.4/lib/rspec/mocks.rb:26:in `proxy_for'
    # /Users/dcarley/vendor/bundle/gems/rspec-mocks-2.14.4/lib/rspec/mocks.rb:51:in `allow_message'
    # /Users/dcarley/vendor/bundle/gems/rspec-mocks-2.14.4/lib/rspec/mocks/syntax.rb:19:in `stub_object'
    # /Users/dcarley/vendor/bundle/gems/rspec-mocks-2.14.4/lib/rspec/mocks/syntax.rb:16:in `block in stub_object'
    # /Users/dcarley/vendor/bundle/gems/rspec-mocks-2.14.4/lib/rspec/mocks/syntax.rb:16:in `each'
    # /Users/dcarley/vendor/bundle/gems/rspec-mocks-2.14.4/lib/rspec/mocks/syntax.rb:16:in `stub_object'
    # /Users/dcarley/vendor/bundle/gems/rspec-mocks-2.14.4/lib/rspec/mocks/syntax.rb:40:in `stub'
    # /Users/dcarley/vendor/bundle/bundler/gems/hiera-puppet-helper-2853187c6553/lib/hiera-puppet-helper.rb:17:in `block (2 levels) in <top (required)>'
    # /Users/dcarley/vendor/bundle/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:237:in `instance_eval'
    # /Users/dcarley/vendor/bundle/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:237:in `instance_eval'
    # /Users/dcarley/vendor/bundle/gems/rspec-core-2.14.7/lib/rspec/core/hooks.rb:21:in `run'
    # /Users/dcarley/vendor/bundle/gems/rspec-core-2.14.7/lib/rspec/core/hooks.rb:85:in `block in run'
    # /Users/dcarley/vendor/bundle/gems/rspec-core-2.14.7/lib/rspec/core/hooks.rb:85:in `each'
    # /Users/dcarley/vendor/bundle/gems/rspec-core-2.14.7/lib/rspec/core/hooks.rb:85:in `run'
    # /Users/dcarley/vendor/bundle/gems/rspec-core-2.14.7/lib/rspec/core/hooks.rb:446:in `run_hook'
    # /Users/dcarley/vendor/bundle/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:345:in `run_before_each_hooks'
    # /Users/dcarley/vendor/bundle/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:294:in `run_before_each'
    # /Users/dcarley/vendor/bundle/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:113:in `block in run'
    # /Users/dcarley/vendor/bundle/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:254:in `with_around_each_hooks'
    # /Users/dcarley/vendor/bundle/gems/rspec-core-2.14.7/lib/rspec/core/example.rb:111:in `run'
    # /Users/dcarley/vendor/bundle/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:390:in `block in run_examples'
    # /Users/dcarley/vendor/bundle/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:386:in `map'
    # /Users/dcarley/vendor/bundle/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:386:in `run_examples'
    # /Users/dcarley/vendor/bundle/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:371:in `run'
    # /Users/dcarley/vendor/bundle/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:372:in `block in run'
    # /Users/dcarley/vendor/bundle/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:372:in `map'
    # /Users/dcarley/vendor/bundle/gems/rspec-core-2.14.7/lib/rspec/core/example_group.rb:372:in `run'
    # /Users/dcarley/vendor/bundle/gems/rspec-core-2.14.7/lib/rspec/core/command_line.rb:28:in `block (2 levels) in run'
    # /Users/dcarley/vendor/bundle/gems/rspec-core-2.14.7/lib/rspec/core/command_line.rb:28:in `map'
    # /Users/dcarley/vendor/bundle/gems/rspec-core-2.14.7/lib/rspec/core/command_line.rb:28:in `block in run'
    # /Users/dcarley/vendor/bundle/gems/rspec-core-2.14.7/lib/rspec/core/reporter.rb:58:in `report'
    # /Users/dcarley/vendor/bundle/gems/rspec-core-2.14.7/lib/rspec/core/command_line.rb:25:in `run'
    # /Users/dcarley/vendor/bundle/gems/rspec-core-2.14.7/lib/rspec/core/runner.rb:80:in `run'
    # /Users/dcarley/vendor/bundle/gems/rspec-core-2.14.7/lib/rspec/core/runner.rb:17:in `block in autorun'