Remove all versions of Puppet gems
This was failing on some machines in Preview because there are multiple
versions of the gem installed:
```
Notice: /Stage[main]/Puppet::Package/Exec[remove_puppet_gem]/returns:
Notice: /Stage[main]/Puppet::Package/Exec[remove_puppet_gem]/returns: Select gem to uninstall:
Notice: /Stage[main]/Puppet::Package/Exec[remove_puppet_gem]/returns:  1. puppet-2.7.18
Notice: /Stage[main]/Puppet::Package/Exec[remove_puppet_gem]/returns:  2. puppet-3.2.3
Notice: /Stage[main]/Puppet::Package/Exec[remove_puppet_gem]/returns:  3. All versions
Notice: /Stage[main]/Puppet::Package/Exec[remove_puppet_gem]/returns: > ERROR:  While executing gem ... (NoMethodError)
Notice: /Stage[main]/Puppet::Package/Exec[remove_puppet_gem]/returns:     undefined method `>=' for nil:NilClass
Error: /usr/bin/gem uninstall --no-executables puppet returned 1 instead of one of [0]
```

Gotta catch em `--all`.