Use default elasticsearch heapsize
The tiny heapsize is causing elasticsearch to throw Java OutOfMemory
errors when trying to run tests:

```
[2016-12-05 12:23:17,498][DEBUG][action.admin.indices.create]
[ci-agent-1.ci.integration.publishing.service.gov.uk]
[page-traffic_test-2016-12-05t12:22:37z-f71d6755-4de1-4421-a9ae-49e309f9fb88] failed to create
java.lang.OutOfMemoryError: Java heap space
```

The agents have plenty of memory available, so let's use the default
heap size used by govuk_elasticsearch class (512MB).