Fix error setting bool value ENV var
https://trello.com/c/YUO21nch

fixes this error:

Error: Parameter content failed on File[/etc/govuk/publishing-api/env.d/SUPPRESS_DRAFT_STORE_502_ERROR]: Munging failed for value true in class content: can't convert true into String at /var/govuk/puppet/modules/govuk/manifests/app/envvar.pp:29

instead setting a string with value '1' serves the same purpose
without causing puppet to fail trying to munge a bool into string.