[64143110] Remove Nagios package and service
This is two-fold:

1. Ensure a clean upgrade from Icinga on `monitoring.management` in Interim
and `monitoring-1.management` in Platform1, both of which currently have
Nagios installed (in addition to Icinga).

2. The `nagios-nrpe-plugin` has `Recommends: nagios3` which causes Nagios to
be installed even on a new machine. Puppet doesn't allow us to pass
`--no-install-recommends`, so this happens:
```
Commandline: /usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install nagios-nrpe-plugin
Install: nagios-nrpe-plugin:amd64 (2.12-5ubuntu1.2), nagios3:amd64 (3.2.3-3ubuntu1, automatic), nagios3-core:amd64 (3.2.3-3ubuntu1, automatic), nagios3-cgi:amd64 (3.2.3-3ubuntu1, automatic), nagios3-common:amd64 (3.2.3-3ubuntu1, automatic)
```

Using `pattern` and `provider` to prevent errors on subsequent runs when the
SysV script has been removed:
```
Error: /Stage[main]/Nagios::Remove/Service[nagios3]: Could not evaluate: Could not find init script or upstart conf file for 'nagios3'
```