Remove `regsubst()` for icinga::check::graphite
These uses of `regsubst()` were added in c2139db3e02c0c1ab635d026fd0ed4d4c407ec23
but `regsubst()` function errors when passing in a number:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: regsubst(): bad target Fixnum:`4294967296' at /usr/share/puppet/production/current/modules/icinga/manifests/check/graphite.pp:81
```

As a value like `@20` won't match the regex it won't be included in
the URL, so the end result is that we won't get a line on the graph.

We can work on adding that later if it's something people need.