[#68432786] govuk_node_class prevent spoofing
Change `govuk_node_class()` to obtain the client's certificate name from the
`$::trusted` hash variable instead of the `$::clientcert` fact in order to
finally prevent spoofing.

This means that the compromise of a relatively boring node like `graphite-1`
will be unable to, for example..

- Request a `mysql_master` catalog and obtain the passwords of all MySQL
  accounts that Puppet manages.
- Register itself in PuppetDB as `logs_redis` node so that other nodes using
  `govuk_node_list` send their `govuk::logstream` logs to it.

The `trusted_node_data` option was added in Puppet 3.4 but won't be enabled
by default until 4.x. This should rollout fine to existing PuppetMasters
because the changes to the function and `puppet.conf` will trigger a reload
of the `puppetmaster` service and then be picked up at the same time shortly
after.

In my testing with Vagrant I occasionally found that the master picked up
the function change before `puppet.conf` got reloaded, because I hit a
unicorn worker that hadn't previously loaded the function (a single client
against 6 workers). But this shouldn't happen in our real environments.

Vagrant users will need to make sure they are using one of the recently
updated base boxes. If you get the following error then you should pull
`gds/puppet` or `alphagov/vagrant-govuk` and destroy your existing box with
`vagrant destroy <node>`:
```
Error: Could not parse application options: invalid option: --trusted_node_data
```