[#65902148] Hiera disk for efg_mysql_slave
So that it stops complaining about a missing mount resource:
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not find resource 'Govuk::Mount[/var/lib/mysql]' for relationship on 'Class[Mysql::Server]' on node efg-mysql-slave-1.efg.production
```

This matches the existing machine in Platform1:
```
dcarley@production-efg-mysql-slave-1:~$ sudo pvs /dev/sdb1
  PV         VG    Fmt  Attr PSize PFree
  /dev/sdb1  mysql lvm2 a-   8.00g    0
dcarley@production-efg-mysql-slave-1:~$ grep mysql /proc/mounts
/dev/mapper/mysql-data /var/lib/mysql ext4 rw,relatime,data=ordered 0 0
```