Remove quotes from Jenkins data sync complete job
These quotes cause the job to fail:

```
ERROR: Failed to build parameters to trigger project: Deploy_App
java.lang.IllegalArgumentException: Illegal choice: "specialist-publisher"
```