install docker before associating docker group to directory
Mirrorer is breaking in production with error:
```
Error: Could not find group docker
Error: /Stage[main]/Govuk_containers::Redis/File[/srv/redis]/group: change from root to docker failed: Could not find group docker
```

This fixes the issue by installing `govuk_docker` (hence have the `docker` group) before giving `docker` group ownership of `/srv/redis` directory