Jenkins Jobs update fix
This was moved to an absolute path in 978b1adf, but moved incorrectly:

```
Error: Could not find command '/usr/bin/jenkins-jobs'
Error: /Stage[main]/Govuk_jenkins::Job_builder_update/Exec[jenkins_jobs_update]/returns: change from notrun to 0 failed: Could not find command '/usr/bin/jenkins-jobs'
Error: /Stage[main]/Govuk_jenkins::Job_builder_update/Exec[jenkins_jobs_update]: Failed to call refresh: Could not find command '/usr/bin/jenkins-jobs'
Error: /Stage[main]/Govuk_jenkins::Job_builder_update/Exec[jenkins_jobs_update]: Could not find command '/usr/bin/jenkins-jobs'
Notice: Finished catalog run in 10.74 seconds
lauramartin@ec2-integration-blue-jenkins-ip-10-1-6-6:~$ which jenkins-jobs
/usr/local/bin/jenkins-jobs
```