Stop notifying ::service when plugin installed
When a new plugin is installed, no longer inform elasticsearch_old::service.
Doing so causes issues with dependencies not being able to be found:

> Error: Could not find dependent Class[Elasticsearch_old::Service] for
> Exec[elasticsearch install plugin head] at
> /var/govuk/puppet/modules/elasticsearch_old/manifests/plugin.pp:44