Make sure mysql_user requires mysql::server
There is a bug logged which I can't reproduce where the following error
message is logged:

```
Error: Could not prefetch mysql_grant provider 'mysql': Command mysql is missing
Error: Command mysql is missing
Error: /Stage[main]/Govuk_mysql::Server::Debian_sys_maint/Govuk_mysql::User[debian-sys-maint@localhost]/Mysql_grant[debian-sys-maint@localhost/*.*]/ensure: change from absent to present failed: Command mysql is missing
```

I believe that is because we are creating that user within the same
class as we are instatiating mysql::server. In reality we should never
be trying to creating users unless we have the mysql server running,
because it's not going to work very well.

Hopefully this [Fixes #66936824] but at the very least it doesn't seem
to make it any worse ;)