Fix removal of RabbitMQ parameters
Paul Bowsher and I have tested and once the user is removed the associated
permissions are also removed. This means that there's no need to
remove these permissions explicitly.

It seems like Puppet might be trying to remove permissions for a user
which no longer exists:

```
Error: /Stage[main]/Govuk::Apps::Content_store::Rabbitmq/Rabbitmq_user_permissions[content_store@/]: Could not evaluate: Command is still failing after 180 seconds expired!
```