Vagrant CI Master ssh key Puppet requires that a correctly formatted string be set for a param belonging to ssh_authorized_key type.
Works around this error when provisioning a ci agent in vagrant:
```
Error: Parameter key failed on Ssh_authorized_key[ci-master-1.ci]: Key must not contain whitespace: In other environments, this should be replaced with a real public key
```