Correct ENV variable declaration for sidekiq-monitoring
This was missing a call to `Govuk::App::Envvar` which led to the
following error running puppet:

```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Must pass app to Govuk::App::Envvar[sidekiq-monitoring-SESSION-KEY] at /usr/share/puppet/production/current/modules/govuk/manifests/apps/sidekiq_monitoring.pp:412 on node i-0ea83cfb2b359c202
```