[#65892432] Fix automongodbbackup mount typos
`s/dba/dbba/`. There are no incorrect mounts to tidy up because Puppet has
been failing to run due to relationship failures:
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not find resource 'Govuk::Mount[/var/lib/automongodbbackup]' for relationship on 'Class[Mongodb::Backup]' on node mongo-1.backend.production
```