Replace mocha syntax in Facter test
Presumably changed by the upgrade to rspec/rspec-mocks. Fixes:
```
Failure/Error: Facter.fact(:fqdn).expects(:value).returns(fqdn)
NoMethodError:
 undefined method `expects' for #<Facter::Util::Fact:0x007fe85a5930b8>
```