[#54520168] Add aptly to mirror apt.puppetlabs
Per the inline comments, what I have in mind is a new external-facing vhost
(e.g. `apt.production.alphagov.co.uk`) that will serve this up to other
environments such as Staging, Preview, Vagrant (in office and VPN), maybe
the Mirrors. We'll either firewall it to our ranges only, or severely rate
limit everyone else.

This will require a bit of manual intervention to completely deploy, because
it doesn't make so much sense to do these things in Puppet. If merged then
I'll write these things up in the opsmanual. Consuming this new repo will
come afterwards.

Create a GPG key which we'll sign our re-published repos with:
```
sudo gpg --gen-key
```

Store in the gds/deployment:creds repo and then publish it:
```
sudo gpg --keyserver keyserver.ubuntu.com --send-keys <KEYID>
```

Sync the mirror and re-publish it:
```
sudo aptly mirror update puppetlabs
sudo aptly snapshot create puppetlabs-$(date +%Y%m%d) from mirror puppetlabs
sudo aptly publish snapshot puppetlabs-$(date +%Y%m%d) puppetlabs
```

I'm using `release => stable` because the PuppetLabs repo doesn't use
different filenames for the per-dist `Packages`. Which causes the following
to happen if we want to mirror Lucid and Precise separately. However since
these are actually the same files we can use the "stable" tag instead.
```
root@apt-1:~# aptly mirror update puppetlabs-lucid
Downloading http://apt.puppetlabs.com/dists/lucid/InRelease...
Downloading http://apt.puppetlabs.com/dists/lucid/Release...
Downloading http://apt.puppetlabs.com/dists/lucid/Release.gpg...
gpgv: Signature made Fri 28 Mar 2014 18:08:40 UTC using RSA key ID 4BD6EC30
gpgv: Good signature from "Puppet Labs Release Key (Puppet Labs Release Key) <info@puppetlabs.com>"
Downloading & parsing package files...
Downloading http://apt.puppetlabs.com/dists/lucid/main/binary-amd64/Packages.bz2...
Downloading http://apt.puppetlabs.com/dists/lucid/main/binary-amd64/Packages.gz...
ERROR: unable to update: unable to save: facter_1.6.12-1puppetlabs1_all, conflict with existing packge
```