Set the licensify Plek URL using hiera $app_domain
This was spotted due to an elavated 5XX rate on the Content API in
staging. The 5XX errors were appearing as exceptions:

**JSON::ParserError: A JSON text must at least contain two octets!**
URL: https://contentapi.staging.publishing.service.gov.uk/premises-licence.json
Exception: https://errbit.staging.publishing.service.gov.uk/apps/538ddb090da115a046000406/problems/55dd9f166578636550980000

All of the exceptions that are logged are for licences where the Content
API tries to query Licensify for the respective information. The Content
API was querying Licensify using the wrong
URL (production.alphagov.co.uk).

Now that we're moving a lot of things over to
`publishing.service.gov.uk` instead of `alphagov.co.uk` we should update
this Plek value to use the `app_domain`.