[#67649440] Upgrade puppet to 3.4.3
So that we can have new shiny:

- Replacement for the anchor pattern
- Policy based auto-signing
- Trusted `clientcert` for `govuk_node_class()`
- Hiera functions in YAML
- A choice of resource ordering

The package change will replace our customised `/usr/bin/puppet` binary and
then Puppet will restore it in the same run.

It will also trigger a restart of the `puppetmaster` process to pick up the
new code. But it may take a few minutes for the workers to switch over
(using unicornherder), during which time there will be warnings like:
```
Notice: Using less secure serialization of reports and query parameters for compatibility
Notice: with older puppet master. To remove this notice, please upgrade your master(s)
Notice: to Puppet 3.3 or newer.
Notice: See http://links.puppetlabs.com/deprecate_yaml_on_network for more information.
```
Or:
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: undefined method `trusted_data=' for #<Puppet::Node:0x000000026b6348>
```

If these errors persist then we should just restart (not reload) the
`puppetmaster` process by hand.