Fix path to Jenkins job templates
The template files were renamed in 2df0d9e418 but the paths referencing
these templates were not updated.

This was causing the Puppet run on `jenkins-1.management` in Production
to fail:

    Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Could not find template 'govuk_jenkins/jobs/production/build_offsite_backup.yaml.erb' at /usr/share/puppet/production/current/modules/govuk_jenkins/manifests/job/build_offsite_backup.pp:8 on node jenkins-1.management.publishing.service.gov.uk