Grafana: Remove smokey constantLine() targets
Graphite returns a 500:
```
Traceback (most recent call last):
  File &quot;/opt/graphite/local/lib/python2.7/site-packages/django/core/handlers/base.py&quot;, line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File &quot;/opt/graphite/webapp/graphite/render/views.py&quot;, line 132, in renderView
    timestamps = range(series.start, series.end, series.step)
TypeError: range() integer end argument expected, got float.
```

Due to bug: https://github.com/graphite-project/graphite-web/issues/375