Revert "Improve postgres nagios alert description"
This reverts commit faf926693981c390aa5b7328d5ccda6dc96bd4b9.

Following this change, Icinga fails to start with:

    Error: The description string for service 'replication on the postgres slave is too far behind master (value in bytes)' on host 'postgresql-slave-1.backend.production' (file '/etc/icinga/conf.d/icinga_host_postgresql-slave-1.backend.production/check_postgres_replication_lag_postgresql-slave-1.cfg', line 5) contains one or more illegal characters.
    Error: The description string for service 'replication on the postgres slave is too far behind master (value in bytes)' on host 'transition-postgresql-slave-1.backend.production' (file '/etc/icinga/conf.d/icinga_host_transition-postgresql-slave-1.backend.production/check_postgres_replication_lag_transition-postgresql-slave-1.cfg', line 5) contains one or more illegal characters.