Raise error if MongoDB replSet configure fails
Previously this would exit with code 0 regardless of whether `rs.initiate()`
was successful or not. The only way to tell it was failing was to see a
resource refreshing on every run:
```
Notice: /Stage[main]/Mongodb::Configure_replica_set/Exec[configure-replica-set]/returns: executed successfully
```

It will now produce the following instead, for example when a replSet member
is missing:
```
Notice: /Stage[main]/Mongodb::Configure_replica_set/Exec[configure-replica-set]/returns: Wed Oct  9 09:58:40 uncaught exception: couldn't initiate : need all members up to initiate, not ok : router-backend-2.router:27017
Notice: /Stage[main]/Mongodb::Configure_replica_set/Exec[configure-replica-set]/returns: failed to load: /etc/mongodb/configure-replica-set.js
Error: /usr/bin/mongo --quiet --host router-backend-1.router /etc/mongodb/configure-replica-set.js returned 253 instead of one of [0]
Error: /Stage[main]/Mongodb::Configure_replica_set/Exec[configure-replica-set]/returns: change from notrun to 0 failed: /usr/bin/mongo --quiet --host router-backend-1.router /etc/mongodb/configure-replica-set.js returned 253 instead of one of [0]
```