Make check_http_timeout_noncrit plugin virtual
This resource gets applied to the development VM since refactoring in
26d83f4. We don't install Icinga there, which causes this error:

    Error: Could not find dependency Class[Icinga::Client::Package] for File[/usr/lib/nagios/plugins/check_http_timeout_noncrit] at /var/govuk/puppet/modules/icinga/manifests/plugin.pp:32

Fix this by making the `icinga::plugin` a virtual resource. This follows a
convention we've used for other resources of this type. They get collected
by `icinga::client`.