Re-add icinga::check::graphite *_command parameters (but ignore them)
Removing these has caused puppet to fail because old exported resources,
which used these parameters, still exist in puppetdb, so you get this
error:

    Error: Could not retrieve catalog from remote server: Error 400 on
    SERVER: Invalid parameter warning_command on node
    monitoring.management.production

This commit temporarily re-adds those parameters until the old resources
have been removed from puppetdb. Please revert once 9e17b79 has been
deployed everywhere (including p1production).